dnl -*- html -*-
define(__timestamp, 2006-06-23T23:50:34Z)dnl
define(__title, `i really need to find some of that obedience lacquer')dnl
define(__id, 49)dnl
include(header.html)
<p>The first day of Railsconf just flew by,  and it's been quite a blast. The highlight of the day was the triple-event combo of Martin Fowler,  Paul Graham,  and Why the Lucky Stiff. Paul Graham talked about the benefits of being an "outsider"&mdash;you can get away with a whole lot more than if you were part of the established order of things. He included his usual jabs at business-as-usual,  and was really thought-provoking and funny. I expect you'll see the essay uploaded in a week or so; read it when you do.</p>
<p>Of course,  you can read all about the events at <a href="http://hagelb.org/railsconf">Planet Railsconf</a>&mdash;there is a whole horde of railsers blogging the events here. However,  I can't sign off tonight without mentioning the fantastic performance of Why and the Thirsty Cups.</p>
<p>Their set was a real treat&mdash;we got a load of songs,  some wild hacks (including one that stumped the inimitable DHH),  and new installments of <i>The Least Surprised</i> and <i>Everyone is Here in the Future</i>. I was quite glad to see that the latter seems to be a serial&mdash;I'm looking forward to the next episodes. I haven't gotten a chance to check it out much,  but _why unveiled <a href="http://balloon.hobix.com">Balloon</a> during his talk,  which seems to be a way of getting your Ruby out to the masses quickly and painlessly.</p>
<p>After the concert I got to head over to talk to _why. He signed my "chunky bacon" t-shirt,  and he got a bunch of present folks (including myself as well as a member of the hotel janitorial staff) to sign a t-shirt of his own,  so it was a fair trade. Afterwards I saw the Thirsty Cups just hanging looking bored,  so I went over to talk with them,  and I got my shirt signed by the whole band. (I'm sure this shirt is now capable of bestowing amazing ruby powers on the wearer,  and I'm quite excited to see how that works out.) Apparently the Cups are not quite into programming and the like,  but they enjoy getting on the road with _why (Trudy is his wife) and love his hijinks,  even if the code is a bit beyond them. (Though let's admit it,  when it comes to _why's code,  it's usually beyond a great many of us!) They seem like a really great crew,  and I hope I can see them perform at another event in the future. (My hopes are high; after all,  <a href="http://redhanded.hobix.com/cult/everyoneIsHereInTheFuture.html">everyone is here,  in the future</a>.)</p>
<p>All in all,  a marvelous day. I will do my best to keep my readers informed here,  but don't skip <a href="http://hagelb.org/railsconf"> Planet Railsconf</a> as there's much more than I could write available there. Also see the <a href="http://flickr.com/photos/tags/railsconf/">Railsconf tag on Flickr</a>.</p>  
include(footer.html)
